chain_name: base
if_init_balance:
  true
FBTC:
  generator_wallet_table:
    true

  daily_sqls:
    address_token_balance:
      - daily_address_token_balances

  period_sqls:
    address_token_balance:
      - period_address_token_balances
    uniswapv3:
      - n_period_feature_holding_balance_uniswap_v3_detail

  py_jobs:
    - address_token_balance
    - farming_uniswapv3
