chain_name: eth

FBTC:
  generator_wallet_table:
    true

  daily_sqls:
    address_token_balance:
      - daily_address_token_balances_1.1
    dodo:
      - daily_feature_erc20_token_supply_records_1.1
    staked:
      - daily_feature_holding_balance_staked_fbtc_detail_1.1
    uniswapv3:
      - daily_feature_holding_balance_uniswap_v3_1.1

  period_sqls:
    address_token_balance:
      - period_address_token_balances
    uniswapv3:
      - period_feature_holding_balance_uniswap_v3_1.1
    staked:
      - period_feature_staked_fbtc_detail_records
      - period_feature_holding_balance_staked_transferred_fbtc_detail
    dodo:
      - period_feature_erc20_token_supply_records
      - period_feature_holding_balance_dodo_eth

  py_jobs:
    - address_token_balance
    - uniswapv3
    - staked
    - dodo
    - eigenlayer

cmETH:
  py_jobs:
    - staked

  generator_wallet_table:
    true