chain_name: hyper

cmETH:
  generator_wallet_table:
    true

  daily_sqls:
    address_token_balance:
      - daily_address_token_balances

  period_sqls:
    address_token_balance:
      - period_address_token_balances

  py_jobs:
    - address_token_balance
