chain_name: mantle

cmETH:
  daily_sqls:
    address_token_balance:
      - daily_address_token_balances

  period_sqls:
    address_token_balance:
      - period_address_token_balances
      - n_period_feature_holding_balance_uniswap_v3_detail
      - period_feature_teahouse_detail