chain_name: sonic

FBTC:
  generator_wallet_table:
    true

  daily_sqls:
    address_token_balance:
      - daily_address_token_balances

  period_sqls:
    address_token_balance:
      - period_address_token_balances
